# docker-compose.yml
version: '3.8'
services:
  bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env.dev # <-- Use the dev file for local development
    restart: unless-stopped