# .github/workflows/deploy.yml

name: Deploy to Production VPS

# Trigger this workflow on every push to the main branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        timeout-minutes: 20
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory
            cd /root/shop-telegram-bot

            # Pull the latest changes from the main branch
            git pull origin master

            # Use docker compose to rebuild and restart the bot in the background
            # This is the professional way to deploy the bot
            docker compose --env-file .env.prod up --build -d